version: '2'
networks:
    bridge:

services:
  orderer0:
    image: rameshthoomu/fabric-orderer-x86_64
    restart: unless-stopped
    environment: 
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_BATCHTIMEOUT=10s
      - ORDERER_GENERAL_BATCHSIZE=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_ORDERERTYPE=solo
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_RAMLEDGER_HISTORY_SIZE=100
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports: 
      - 5005:5005
    container_name: orderer0
    networks: 
      - bridge

  peer0:
    image: rameshthoomu/fabric-peer-x86_64
    restart: unless-stopped
    environment: 
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_NETWORKID=peer0
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes: 
      - /var/run:/host/var/run/
    command: peer node start
    links: 
      - orderer0
    ports: 
      - 7051:7051
    container_name: peer0
    networks: 
      - bridge

  cli:
    container_name: cli
    image: rameshthoomu/fabric-peer-x86_64
    tty: true
    environment: 
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:5005
      - CORE_PEER_ADDRESS=peer0:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/sh
    links: 
      - orderer0:orderer0
      - peer0:peer0
    volumes: 
      - /var/run/:/host/var/run/
      - /opt/gopath/src/github.com/hyperledger/fabric/examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    depends_on: 
      - orderer0
      - peer0
    networks: 
      - bridge

